/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marissa
 */
public class ProgramAritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;

    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        b1.setVisible(false);
        bil4.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(114, 31, 290, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(61, 88, 129, 22);

        jenis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(287, 85, 151, 28);

        panel.setBackground(new java.awt.Color(102, 102, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ket.setBackground(new java.awt.Color(255, 102, 102));
        ket.setText("Ket");
        panel.add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 27, 109, 22));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 78, -1, -1));

        b1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b1.setText("Bilangan 1");
        panel.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 124, -1, -1));

        b2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b2.setText("Bilangan 2");
        panel.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 183, -1, -1));

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b3.setText("Bilangan 3");
        panel.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 249, -1, -1));

        b4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b4.setText("Bilangan 4");
        panel.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 313, -1, -1));

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 77, 156, 28));

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 123, 156, 29));
        panel.add(bil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 181, 156, 31));
        panel.add(bil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 247, 156, 30));
        panel.add(bil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 311, 156, 30));

        hitung.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 359, 92, 43));

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 408, 262, 118));

        getContentPane().add(panel);
        panel.setBounds(32, 131, 474, 544);

        setBounds(0, 0, 549, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
      setJenis();
    }
      private void setJenis() {
        if(jenis.getSelectedItem().equals("Penjumlahan")) {
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")) {
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")) {
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")) {
        jns = "Pembagian";
        ket.setText("Pembagian");
        panel.setVisible(true);
        pilihanbil.setVisible(true);
    }
    
    }//GEN-LAST:event_jenisActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());


        if (jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                hasil.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                hasil.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                hasil.setText(""+a1+" : "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                hasil.setText(""+a1+" : "+a2+" : "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                hasil.setText(""+a1+" : "+a2+" : "+a3+" : "+a4+" = "+hsl);
            }
        }
        if (jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                hasil.setText(""+a1+" x "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" x "+a4+" = "+hsl);
            }
        }

    }//GEN-LAST:event_hitungActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables

    private void getJumlah() {
     if(pilihanbil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2;
        }
        else if(pilihanbil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 3;
        }
        else if(pilihanbil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 4;
        }
    }

    

 
}
